### ISSUE TITLE
NoSuchMethodError: No virtual method getContext

### ISSUE THREAD

**Issue by RicardoBelchior** [VerveWireless/verve-android-adsdk#14]
Hi,

After upgrading some libraries (which we had to , because of other dependencies), Verve has started to crash with the following exception:

> 03-30 12:11:41.219 11272-11272/com.mirror.news.debug E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                        Process: com.mirror.news.debug, PID: 11272
>                                                                        java.lang.NoSuchMethodError: No virtual method getContext()Landroid/content/Context; in class Lcom/google/android/gms/common/api/GoogleApiClient; or its super classes (declaration of 'com.google.android.gms.common.api.GoogleApiClient' appears in /data/app/com.mirror.news.debug-5bwpsf6ae2wr5Fbb4Qm00g==/base.apk!classes4.dex)
>                                                                            at com.vervewireless.advert.b.b.b(SourceFile:178)
>                                                                            at com.vervewireless.advert.b.b$a.onConnected(SourceFile:198)
>                                                                            at com.google.android.gms.common.internal.zzae.zza(Unknown Source:109)
>                                                                            at com.google.android.gms.common.api.internal.zzba.zza(Unknown Source:22)
>                                                                            at com.google.android.gms.common.api.internal.zzao.zzf(Unknown Source:89)
>                                                                            at com.google.android.gms.common.api.internal.zzao.zza(Unknown Source:21)
>                                                                            at com.google.android.gms.common.api.internal.zzbi.onConnected(Unknown Source:7)
>                                                                            at com.google.android.gms.common.api.internal.zzt.onConnected(Unknown Source:5)
>                                                                            at com.google.android.gms.common.internal.zzac.zza(Unknown Source:2)
>                                                                            at com.google.android.gms.common.internal.zzn.zza(Unknown Source:148)
>                                                                            at com.google.android.gms.common.internal.zze.zza(Unknown Source:48)
>                                                                            at com.google.android.gms.common.internal.zzi.zzc(Unknown Source:57)
>                                                                            at com.google.android.gms.common.internal.zzh.handleMessage(Unknown Source:275)
>                                                                            at android.os.Handler.dispatchMessage(Handler.java:106)
>                                                                            at android.os.Looper.loop(Looper.java:164)
>                                                                            at android.app.ActivityThread.main(ActivityThread.java:6494)
>                                                                            at java.lang.reflect.Method.invoke(Native Method)
>                                                                            at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
>                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
> 

Here's our setup now:
>     androidMinSdkVersion = 17
>     androidCompileSdkVersion = 27
>     androidTargetSdkVersion = 27
>     supportLibraryVersion = '27.1.0'
>     playServicesVersion = '12.0.0'
>     AGP = '3.0.1'
>     GoogleServices = '3.2.0'

If I comment out `VerveAdSDK.initialize(...)` , the app doesn't crash anymore.
I suspect it's related with the play services... can you please make sure your libraries are up-to-date?

**Comment by christinamatthews** [comment]
Thank you for sending across this information @RicardoBelchior. We are investigating this issue and will get back to you with a response as soon as possible.

**Comment by christinamatthews** [comment]
@RicardoBelchior  - After investigating, we've discovered that this is caused by some deprecated methods in Google Play Services v12.0.0. We currently do not support this version of GPS, however it will be supported in our next release.

**Comment by RicardoBelchior** [comment]
Thanks @christinamatthews . Can you give us an ETA for that next release? 

I'm asking because due to integrations with other services we were forced to update GooglePlayServices, but are now stuck due to this issue.

**Comment by christinamatthews** [comment]
@RicardoBelchior - We are looking at having it out in ~2 weeks.
